- name: install commonsoft
  apt: pkg={{ item }}
  with_items:
    - iftop
    - tcpdump
    - wget
    - curl
    - monit
    - dos2unix
    - nmap
  environment:
    PATH: /usr/sbin:/sbin/:{{ ansible_env.PATH }}
