- name: ohmyzsh repo
  git: repo=https://github.com/korjavin/oh-my-zsh.git dest=/home/iv/.oh-my-zsh depth=1 version=master
  sudo: yes
  sudo_user: iv

- name: ohmyzsh repo right
  action: file path=/home/iv/.oh-my-zsh group=iv owner=iv state=directory recurse=yes

- name: zsh config
  copy: src="zshrc" dest="/home/iv/.zshrc" owner=iv group=iv mode=0644

- name: zsh config1
  copy: src="zshenv" dest="/home/iv/.zshenv" owner=iv group=iv mode=0644

- name: histor right
  action: file path=/home/iv/.zsh_history group=iv owner=iv state=touch

- name: ssh-keyscan the git server #https://github.com/ansible/ansible/issues/7474
  shell: ssh-keyscan -H -t dsa github.com >> ~/.ssh/known_hosts 2>&1

- name:  iv tmp dir
  action: file path=/home/iv/tmp group=iv owner=iv mode=700 state=directory

- name:  iv tmp dir
  action: file path=/home/iv/tmp/vim group=iv owner=iv mode=700 state=directory

- name:  iv bin dir
  action: file path=/home/iv/bin group=iv owner=iv mode=700 state=directory recurse=yes

- name: git config
  copy: src="gitconfig" dest="/home/iv/.gitconfig"

- name: screen config
  copy: src="screenrc" dest="/home/iv/.screenrc"


- name: vim conf
  copy: src="vimrc" dest="/home/iv/.vimrc" owner=iv group=iv mode=0644

- name: vimrepo
  git: repo=https://github.com/korjavin/vimfiles.git dest=/home/iv/.vim version=master accept_hostkey=yes force=yes recursive=yes
  ignore_errors: yes

- name: vimrepo right
  action: file path=/home/iv/.vim group=iv owner=iv state=directory recurse=yes

