- mysql_db:
      name=db1
      state=absent
      login_host=127.0.0.1
      encoding=utf8

- mysql_db:
      name=db1
      state=present
      login_host=127.0.0.1
      encoding=utf8

- name: download locally
  local_action: get_url http://localhost:8081/service/local/artifact/maven/redirect?r=sql&g=db&a=db1&p=bz2&v=LATEST

- copy: src=db1.sql.bz2 dest=/tmp

- mysql_db:
      name=db1
      state=import
      target=/tmp/db1.sql.bz2
      login_host=127.0.0.1

- file: path=/tmp/db1.sql.bz2 state=absent


- mysql_user:
      name=user12
      host=%
      password=12345aa
      priv=db1.*:ALL,GRANT/*.*:FILE
      state=present
      login_host=127.0.0.1
