- group: name=iv state=present

  #- name: Add User Iv
# python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
- user: name='iv' shell='/usr/bin/zsh' group='iv' #password='$1$SomeSalt$.97jlnH5r3aQGJO4F.UNS1'

- name: Ivan key
  authorized_key: user=iv
                  key="{{ lookup('file', '/home/iv/.ssh/id_rsa.pub') }}"
  ignore_errors: yes

- name: Ivan key for root
  authorized_key: user=root
                  key="{{ lookup('file', '/home/iv/.ssh/id_rsa.pub') }}"
  ignore_errors: yes

- name: ohmyzsh repo
  git: repo=https://github.com/korjavin/oh-my-zsh.git dest=/home/iv/.oh-my-zsh depth=1 version=master
  become: yes
  become_user: iv

- name: ohmyzsh repo right
  action: file path=/home/iv/.oh-my-zsh group=iv owner=iv state=directory recurse=yes

- name: zsh config
  copy: src="zshrc" dest="/home/iv/.zshrc" owner=iv group=iv mode=0644

- name: zsh config1
  copy: src="zshenv" dest="/home/iv/.zshenv" owner=iv group=iv mode=0644

- name: sudoers
  lineinfile: 'dest="/etc/sudoers" line="iv ALL=(ALL) NOPASSWD: ALL"'

- name: ssh-keyscan the git server #https://github.com/ansible/ansible/issues/7474
  shell: ssh-keyscan -H -t dsa github.com >> ~/.ssh/known_hosts 2>&1

- name:  iv tmp dir
  action: file path=/home/iv/tmp group=iv owner=iv mode=700 state=directory

- name:  iv bin dir
  action: file path=/home/iv/bin group=iv owner=iv mode=700 state=directory recurse=yes

- name: git config
  copy: src="gitconfig" dest="/home/iv/.gitconfig"

- name: screen config
  copy: src="screenrc" dest="/home/iv/.screenrc"

- name: history right
  action: file path=/home/iv/.zsh_history group=iv mode=700 owner=iv state=touch

- name: vim conf
  copy: src="vimrc" dest="/home/iv/.vimrc" owner=iv group=iv mode=0644

- name: vimrepo
  git: repo=https://github.com/korjavin/vimfiles.git dest=/home/iv/.vim version=master accept_hostkey=yes force=yes recursive=yes
  ignore_errors: yes

- name: vimrepo right
  action: file path=/home/iv/.vim group=iv owner=iv state=directory recurse=yes

