- name: testing repo
  apt_repository: repo='deb http://mirror.yandex.ru/debian/ testing main contrib non-free' state=present
- name: update
  apt: update_cache=yes
- name: upgrade
  apt: upgrade=full
  ignore_errors: yes
- name: install -f
  command: apt-get -y install -f
  ignore_errors: yes
- name: upgrade second try
  apt: upgrade=full
  ignore_errors: yes
- name: install -f second try
  command: apt-get -y install -f
  ignore_errors: yes
- name: upgrade third try
  apt: upgrade=full
  ignore_errors: yes
- name: install locales
  apt: pkg=locales
- locale_gen: name=ru_RU.UTF-8 state=present
- name: clean
  command: apt-get -y autoclean
